#!/usr/bin/env bash

CHECK_ARG=

case $1 in
    -h)
        echo "$0 [-c]"
        ;;
    -c)
        CHECK_ARG=-c
        ;;
esac

find . -name '*.nix' \
  -exec nix run nixpkgs#nixfmt "--" $CHECK_ARG {} +
